/**
 * @swagger
 * components:
 *   schemas:
 *     item:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description : Auto generated by the database
 *         fk_utente:
 *           type: integer
 *         nome:
 *           type: string
 *         prezzo:
 *           type: float
 *         descrizione:
 *           type: string
 *         immagine:
 *           type: Ole Object
 *         tags:
 *           type: array
 *           items:
 *             type: integer
 */

import express from 'express'
import {
  getItemById,
  getAllItems,
  createItem,
  addItemToFavorites,
  deleteItemById,
  removeItemFromFavorites,
  getFavoriteItemsByUserId,
  getCartItemsByUserId,
  updateItemById,
  isItemInFavorites,
  isItemInCart,
  addItemToCart,
  removeItemFromCart
} from '../utils/item_utils.js'
import { isAuthenticated, createChat, checkChatExist } from '../utils/user_utils.js'

const router = express.Router()

/**
 * @swagger
 * /items:
 *   get:
 *     tags: ["item"]
 *     summary: Mostra tutti gli elementi
 *     description: Restituisce tutti gli elementi presenti nel database come json array
 *     responses:
 *       200:
 *         description: Lista di prodotti inviata
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   descrizione:
 *                     type: string
 *
 *       500:
 *         description: Errore interno del server
 */
router.get('/items', isAuthenticated, async (req, res) => {
  try {
    res.statusCode = 200
    res.send(await getAllItems())
  } catch (err) {
    res.statusCode = 401
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna un prodotto
 *     description: Ritorna i dettagli di un prodotto specifico
 *     responses:
 *       200:
 *         description: Oggetto ritornato con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 fk_utente:
 *                   type: integer
 *                 prezzo:
 *                   type: float
 *                 descrizione:
 *                   type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/items/:itemId', isAuthenticated, async (req, res) => {
  try {
    const itemId = req.params.itemId
    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.send(await getItemById(itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   get:
 *     tags: ["item"]
 *     summary: Crea una chat partendo dall'oggetto
 *     description: Ritorna i dettagli di un prodotto specifico
 *     responses:
 *       200:
 *         description: Chat creata con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 fk_utente:
 *                   type: integer
 *                 prezzo:
 *                   type: float
 *                 descrizione:
 *                   type: string
 *       500:
 *         description: Errore interno del server
 */

router.post('/items/chats/:itemId', isAuthenticated, async (req, res) => {
  try {
    const itemId = req.params.itemId
    const userId1 = req.session.user.id
    const item = await getItemById(itemId)
    const chatExist = await checkChatExist(item.fk_utente, userId1)
    
    if (chatExist.length > 0) {
        res.statusCode = 401
        res.setHeader('Content-Type', 'application/json')
        return res.end(JSON.stringify({ error: "Chat già esistente" }))
    }
    const chat = await createChat(userId1, item.fk_utente)

    res.setHeader('Content-Type', 'application/json')
    res.status(201)
    res.end(JSON.stringify(chat))
  } catch (error) {
    console.error(error)
  }
})


/**
 * @swagger
 * /items:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto
 *     description: Inserisce un nuovo oggetto nel db
 *     responses:
 *       201:
 *         description: Oggetto aggiunto con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 prod_id:
 *                   type: integer
 *       500:
 *         description: Errore interno del server
 */
router.post('/items', isAuthenticated, async (req, res) => {
  try {
    const { picture, name, price, description, fk_tag } = req.body
    if (!picture || !name || !price || !description || !fk_tag) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(
        JSON.stringify({
          error: 'Non sono stati inseriti tutti i parametri necessari per eseguire la funzione'
        })
      )
    }

    const userId = req.session.user.id
    const now = new Date()
    const formattedDate = now.getDate() + '-' + (now.getMonth() + 1) + '-' + now.getFullYear()

    const createdItem = await createItem(picture, name, price, description, formattedDate, userId, fk_tag)

    res.statusCode = 201
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(createdItem))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dal database
 *     description: Rimuove un prodotto dal database in base all'id e lo ritorna
 *     responses:
 *       204:
 *         description: Prodotto eliminato
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/:itemId', isAuthenticated, async (req, res) => {
  try {
    const itemId = req.params.itemId
    const userId = req.session.user.id
    const existingItem = await getItemById(itemId)

    if (existingItem === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }

    if (existingItem.fk_utente !== userId) {
      res.status(500)
      return res.end()
    }

    res.send(await deleteItemById(itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/favorites:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto alla lista dei preferiti
 *     description: Aggiungere un record dove l'utente e l'oggetto sono collegati
 *     responses:
 *       204:
 *         description: Oggetto aggiunto con successo
 *       500:
 *         description: Errore interno del server
 */
router.post('/items/favorites', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const { itemId } = req.body
    const item = await getItemById(itemId)
    if (item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkFavorite = await isItemInFavorites(userId, itemId)
    if ( checkFavorite.lenght > 0) {
      res.statusCode = 204
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto già presente fra i preferiti' }))
    }
    const add = await addItemToFavorites(userId, itemId)
    res.send(add)
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/favorites:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dai preferiti
 *     description: Cancella un record dalla tabella che collega il prodotto ai preferiti dell'utente
 *     responses:
 *       204:
 *         description: Prodotto eliminato dai Preferiti
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/favorites/:itemId', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const itemId = req.params.itemId
    const item = await getItemById(itemId)
    if ( item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkFavorite = await isItemInFavorites(userId, itemId)
    if ( checkFavorite.lenght > 0) {
      res.statusCode = 400
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto non presente fra i preferiti' }))
    }

    res.statusCode = 204
    res.send(await removeItemFromFavorites(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/cart:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto al carello
 *     description: Aggiungere un record alla tabella di collegamento fra utente e prodotto
 *     responses:
 *       204:
 *         description: Oggetto aggiunto con successo
 *       500:
 *         description: Errore interno del server
 */
router.post('/items/cart', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const { itemId } = req.body
    const item = await getItemById(itemId) 

    if (item.lenght > 0) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }

    res.send(await addItemToCart(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/cart:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dal carrello
 *     description: Cancellare un record della tabella carrello
 *     responses:
 *       204:
 *         description: Prodotto eliminato dai Preferiti
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/cart/:itemId', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const itemId = req.params.itemId
    const item = await  getItemById(itemId)
    if ( item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkCart = await isItemInCart(userId, itemId)
    if (checkCart.affectedRows === 0) {
      res.statusCode = 400
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto non presente nel carello' }))
    }

    res.send(await removeItemFromCart(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /cart:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna tutti gli elementi nel carrello
 *     description: Ritorna tutti gli elementi nel carrello di un'utente dato l'id
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */


/*router.get('/cart', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const cartItems = await getCartItemsByUserId(userId)
    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(cartItems))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})*/
router.get('/cart', isAuthenticated, async (req, res) => {
  try {

    const userId = req.session.user?.id
    const cartItems = await getCartItemsByUserId(userId)


    return res.status(200).json(cartItems)
  } catch (err) {
    console.error('CART ERROR:', err)
    return res.status(500).json({ error: String(err) })
  }
})


/**
 * @swagger
 * /favorites:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna tutti gli elementi nei preferiti
 *     description: Ritorna tutti gli elementi nei preferiti di un'utente dato l'id
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/favorites', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
  
    const favoriteItems = await getFavoriteItemsByUserId(userId)
    
    return res.status(200).json(favoriteItems)
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/update:
 *   patch:
 *     tags: ["item"]
 *     summary: Modifica un'elemento
 *     description: Modifica delle informazioni di un'elemento
 *     responses:
 *       200:
 *         description: Info Modificate
 *       500:
 *         description: Errore interno del server
 */
router.patch('/items/update', isAuthenticated, async (req, res) => {
  try {
    const { id: itemId, price, picture, description, name, fk_tag } = req.body
    console.log(itemId)
    console.log(name)

    if (!picture || !name || !price || !description || !fk_tag || !itemId) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(
        JSON.stringify({
          error: 'Non sono stati inseriti tutti i parametri necessari per eseguire la funzione'
        })
      )
    }

    const existingItem = await getItemById(itemId)

    if (existingItem === undefined) {
      res.status(500)
      return res.end()
    }

    if (existingItem.fk_utente !== req.session.user.id) {
      res.status(500)
      return res.end()
    }

    const updatedItem = await updateItemById(itemId, price, picture, description, name, fk_tag)

    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end()
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

export { router }
