/**
 * @swagger
 * components:
 *   schemas:
 *     tag:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description : Auto generated by the database
 *         nome:
 *           type: string
 *         descrizione:
 *           type: string
 */
import express from 'express'
import { findItemsByTagId, findItemsByName, getAllTags } from '../utils/search_utils.js'
import { isAuthenticated } from '../utils/user_utils.js'

const router = express.Router()

/**
 * @swagger
 * /tags:
 *   get:
 *     tags: ["search"]
 *     summary: Ritorna la lista con tutti i tag
 *     description: Cerca nel db tutti i tag e ne restituisce l'elenco
 *     responses:
 *       200:
 *         description: tag inviati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   nome:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/tags', isAuthenticated, async (req, res) => {
  try {
    const tags = await getAllTags()
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(tags))
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /tag/{tagId}:
 *   get:
 *     tags: ["search"]
 *     summary: Cerca gli oggetti con un tag
 *     description: Cerca tutti gli oggetti presenti nel db con un determinato tag
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/tag/:tagId', isAuthenticated, async (req, res) => {
  try {
    const tagId = req.params.tagId
    const items = await findItemsByTagId(tagId)
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(items))
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /name/{name}:
 *   get:
 *     tags: ["search"]
 *     summary: Cerca gli oggetti con una data parola nel nome
 *     description: Cerca tutti gli oggetti presenti nel db che contengono la stringa data nel nome
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/name/:name', isAuthenticated, async (req, res) => {
  try {
    const name = req.params.name
    const namePattern = '%' + name + '%'
    const items = await findItemsByName(namePattern)
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(items))
  } catch (error) {
    console.error(error)
  }
})

export { router }
