/**
 * @swagger
 * components:
 *   schemas:
 *     item:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description : Auto generated by the database
 *         fk_utente:
 *           type: integer
 *         nome:
 *           type: string
 *         prezzo:
 *           type: float
 *         descrizione:
 *           type: string
 *         immagine:
 *           type: Ole Object
 *         tags:
 *           type: array
 *           items:
 *             type: integer
 */

import express from 'express'
import {
  getItemById,
  getAllItems,
  createItem,
  addItemToFavorites,
  deleteItemById,
  removeItemFromFavorites,
  getFavoriteItemsByUserId,
  getCartItemsByUserId,
  updateItemById,
  isItemInFavorites,
  isItemInCart,
  addItemToCart,
  removeItemFromCart,
  newAuction,
  newOffer,
  infoAuction,
  infoOffer,
  addTimeAuction,
  changeWinningOffer,
  findOffer,
  setNewTime,
  getOpenAuctionsRich,
  getAuctionDetailRich,
  getOffersByAuctionId,
  getAuctionsByOwnerIdRich,
} from '../utils/item_utils.js'
import multer from 'multer'
import { isAuthenticated, createChat, checkChatExist } from '../utils/user_utils.js'
import { extendAuctionIfSniping, closeAuctionAndNotify, getAuctionOwnerId } from '../utils/auction_utils.js';
const upload = multer({ dest: 'uploads/items' });



const router = express.Router()

/**
 * @swagger
 * /items:
 *   get:
 *     tags: ["item"]
 *     summary: Mostra tutti gli elementi
 *     description: Restituisce tutti gli elementi presenti nel database come json array
 *     responses:
 *       200:
 *         description: Lista di prodotti inviata
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   descrizione:
 *                     type: string
 *
 *       500:
 *         description: Errore interno del server
 */
router.get('/items/:nr', async (req, res) => {
  try {
    const nr = Number(req.params.nr)
    res.statusCode = 200
    const response = await getAllItems()
    res.send(response.slice((nr-1)*30, Math.min(nr*30 -1, (response.length-1))))
  } catch (err) {
    res.statusCode = 401
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna un prodotto
 *     description: Ritorna i dettagli di un prodotto specifico
 *     responses:
 *       200:
 *         description: Oggetto ritornato con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 fk_utente:
 *                   type: integer
 *                 prezzo:
 *                   type: float
 *                 descrizione:
 *                   type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/itemsId/:itemId', async (req, res) => {
  try {
    const itemId = req.params.itemId
    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.send(await getItemById(itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   get:
 *     tags: ["item"]
 *     summary: Crea una chat partendo dall'oggetto
 *     description: Ritorna i dettagli di un prodotto specifico
 *     responses:
 *       200:
 *         description: Chat creata con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 fk_utente:
 *                   type: integer
 *                 prezzo:
 *                   type: float
 *                 descrizione:
 *                   type: string
 *       500:
 *         description: Errore interno del server
 */

router.post('/items/chats/:itemId', isAuthenticated, async (req, res) => {
  try {
    const itemId = req.params.itemId
    const userId1 = req.session.user.id
    const item = await getItemById(itemId)
    const chatExist = await checkChatExist(item.fk_utente, userId1)

    if (chatExist.length > 0) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: "Chat già esistente" }))
    }
    const chat = await createChat(userId1, item.fk_utente)

    res.setHeader('Content-Type', 'application/json')
    res.status(201)
    res.end(JSON.stringify(chat))
  } catch (error) {
    console.error(error)
  }
})


/**
 * @swagger
 * /items:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto
 *     description: Inserisce un nuovo oggetto nel db
 *     responses:
 *       201:
 *         description: Oggetto aggiunto con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 prod_id:
 *                   type: integer
 *       500:
 *         description: Errore interno del server
 */
router.post('/items', isAuthenticated,  upload.single('prod_img'), async (req, res) => {
  try {
    const { name, price, description, fk_tag } = req.body
    if ( !name || !price || !description || !fk_tag) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(
        JSON.stringify({
          error: 'Non sono stati inseriti tutti i parametri necessari per eseguire la funzione'
        })
      )
    }

    const userId = req.session.user.id
    const picture = `http://127.0.0.1:${process.env.BACKEND_PORT}/uploads/items/${req.file.filename}`
    const now = new Date()
    const formattedDate = now.getFullYear() +
      '-' +
      (now.getMonth() + 1) +
      '-' +
      now.getDate() +
      ' ' +
      now.getHours() +
      ':' +
      now.getMinutes()

    const createdItem = await createItem(picture, name, price, description, formattedDate, userId, fk_tag)

    res.statusCode = 201
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(createdItem))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dal database
 *     description: Rimuove un prodotto dal database in base all'id e lo ritorna
 *     responses:
 *       204:
 *         description: Prodotto eliminato
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/:itemId', isAuthenticated, async (req, res) => {
  try {
    const itemId = req.params.itemId
    const userId = req.session.user.id
    const existingItem = await getItemById(itemId)

    if (existingItem === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }

    if (existingItem.fk_utente !== userId) {
      res.status(500)
      return res.end()
    }

    res.send(await deleteItemById(itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/favorites:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto alla lista dei preferiti
 *     description: Aggiungere un record dove l'utente e l'oggetto sono collegati
 *     responses:
 *       204:
 *         description: Oggetto aggiunto con successo
 *       500:
 *         description: Errore interno del server
 */
router.post('/items/favorites/:iteamId', isAuthenticated, async (req, res) => {
  try {

    const userId = req.session.user.id
    const itemId = req.params.iteamId
    const item = await getItemById(itemId)
    if (item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkFavorite = await isItemInFavorites(userId, itemId)
    if (checkFavorite.length === 0) {
      res.statusCode = 204
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto già presente fra i preferiti' }))
    }
    const add = await addItemToFavorites(userId, itemId)
    res.send(add)
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/favorites:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dai preferiti
 *     description: Cancella un record dalla tabella che collega il prodotto ai preferiti dell'utente
 *     responses:
 *       204:
 *         description: Prodotto eliminato dai Preferiti
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/favorites/:itemId', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const itemId = req.params.itemId
    const item = await getItemById(itemId)
    if (item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkFavorite = await isItemInFavorites(userId, itemId)
    if (checkFavorite.length === 0) {
      res.statusCode = 400
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto non presente fra i preferiti' }))
    }

    res.statusCode = 204
    res.send(await removeItemFromFavorites(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/cart:
 *   post:
 *     tags: ["item"]
 *     summary: Aggiunge un'oggetto al carello
 *     description: Aggiungere un record alla tabella di collegamento fra utente e prodotto
 *     responses:
 *       204:
 *         description: Oggetto aggiunto con successo
 *       500:
 *         description: Errore interno del server
 */
router.post('/items/cart/:iteamId', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const itemId = req.params.iteamId
    const item = await getItemById(itemId)

    if (item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }

    res.send(await addItemToCart(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/{itemId}/cart:
 *   delete:
 *     tags: ["item"]
 *     summary: Rimuove un prodotto dal carrello
 *     description: Cancellare un record della tabella carrello
 *     responses:
 *       204:
 *         description: Prodotto eliminato dai Preferiti
 *       500:
 *         description: Errore interno del server
 */
router.delete('/items/cart/:itemId', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const itemId = req.params.itemId
    const item = await getItemById(itemId)
    if (item === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }
    const checkCart = await isItemInCart(userId, itemId)
    if (checkCart.length === 0) {
      res.statusCode = 400
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto non presente nel carello' }))
    }

    res.send(await removeItemFromCart(userId, itemId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /cart:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna tutti gli elementi nel carrello
 *     description: Ritorna tutti gli elementi nel carrello di un'utente dato l'id
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */


/*router.get('/cart', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const cartItems = await getCartItemsByUserId(userId)
    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(cartItems))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})*/
router.get('/cart', isAuthenticated, async (req, res) => {
  try {

    const userId = req.session.user?.id
    const cartItems = await getCartItemsByUserId(userId)


    return res.status(200).json(cartItems)
  } catch (err) {
    console.error('CART ERROR:', err)
    return res.status(500).json({ error: String(err) })
  }
})


/**
 * @swagger
 * /favorites:
 *   get:
 *     tags: ["item"]
 *     summary: Ritorna tutti gli elementi nei preferiti
 *     description: Ritorna tutti gli elementi nei preferiti di un'utente dato l'id
 *     responses:
 *       200:
 *         description: Oggetti ritornati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente:
 *                     type: integer
 *                   prezzo:
 *                     type: float
 *                   immagine:
 *                     type: string
 *                   descrizione:
 *                     type: string
 *                   dataCreazione:
 *                     type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/favorites', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id

    const favoriteItems = await getFavoriteItemsByUserId(userId)

    return res.status(200).json(favoriteItems)
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/update:
 *   patch:
 *     tags: ["item"]
 *     summary: Modifica un'elemento
 *     description: Modifica delle informazioni di un'elemento
 *     responses:
 *       200:
 *         description: Info Modificate
 *       500:
 *         description: Errore interno del server
 */
router.patch('/items/update', isAuthenticated, async (req, res) => {
  try {
    const { id: itemId, price, picture, description, name, fk_tag } = req.body


    if (!picture || !name || !price || !description || !fk_tag || !itemId) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(
        JSON.stringify({
          error: 'Non sono stati inseriti tutti i parametri necessari per eseguire la funzione'
        })
      )
    }

    const existingItem = await getItemById(itemId)

    if (existingItem === undefined) {
      res.status(500)
      return res.end()
    }

    if (existingItem.fk_utente !== req.session.user.id) {
      res.status(500)
      return res.end()
    }

    const updatedItem = await updateItemById(itemId, price, picture, description, name, fk_tag)

    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end()
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/auction/createAuction:
 *   post:
 *     tags: ["item"]
 *     summary: Apre una nuova asta
 *     description: Crea una nuova asta se l'oggetto scelto appartiene all'utente loggato
 *     responses:
 *       200:
 *         description: Info Modificate
 *       500:
 *   
 * 
 */
/*router.post('/items/auction/createAuction', isAuthenticated, async(req, res) => {
  try {
    const userId = req.session.user.id
    const { itemId, dataI, minPrice, dataF} = req.body
    

    //const item = await getItemById(itemId)

    if (item.length > 0) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Oggetto inesistente' }))
    }

    if(item.fk_utente === userId){
      const newAct = await newAuction(itemId, dataI, minPrice, dataF)
    }

    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end()//
    const item = await getItemById(itemId);

    if (!item) {
      return res.status(404).json({ error: 'Oggetto inesistente' });
    }

    if (item.fk_utente !== userId) {
      return res.status(403).json({ error: 'Non sei il proprietario' });
    }

    await newAuction(itemId, dataI, minPrice, dataF);
    return res.status(200).end();
    
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})*/

/*
router.post('/items/auction/createAuction', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id;
    const { itemId, dataI, minPrice, dataF } = req.body;

    const item = await getItemById(itemId);

    if (!item) {
      return res.status(404).json({ error: 'Oggetto inesistente' });
    }

    if (item.fk_utente !== userId) {
      return res.status(403).json({ error: 'Non sei il proprietario dell’oggetto' });
    }

    await newAuction(itemId, dataI, minPrice, dataF);
    return res.status(200).end();
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});*/

router.post('/items/auction/createAuction', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id;
    const { itemId, dataI, minPrice, dataF } = req.body;

    const item = await getItemById(itemId);

    if (!item) {
      return res.status(404).json({ error: 'Oggetto inesistente' });
    }

    if (item.fk_utente !== userId) {
      return res.status(403).json({ error: 'Non sei il proprietario dell’oggetto' });
    }

    await newAuction(itemId, dataI, minPrice, dataF);
    return res.status(200).end();
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});


// LISTA ASTE APERTE (ricca) -> serve per /aste
router.get('/items/auction/open', async (req, res) => {
  try {
    const rows = await getOpenAuctionsRich();
    return res.status(200).json(rows);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});

// DETTAGLIO ASTA (ricco) + ultime offerte
router.get('/items/auction/detail/:auctionId', async (req, res) => {
  try {
    const { auctionId } = req.params;

    const auction = await getAuctionDetailRich(auctionId);
    if (!auction) return res.status(404).json({ error: 'Asta non trovata' });

    const offers = await getOffersByAuctionId(auctionId, 10);
    return res.status(200).json({ auction, offers });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});

router.get('/items/auction/user/:userId', async (req, res) => {
  try {
    const userId = req.params.userId;
    res.status(200).json(await getAuctionsByOwnerIdRich(userId));
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: String(err) });
  }
});

router.patch('/items/auction/:auctionId/close', isAuthenticated, async (req, res) => {
  try {
    const { auctionId } = req.params;

    const ownerId = await getAuctionOwnerId(auctionId);
    if (!ownerId) return res.status(404).json({ error: 'Asta non trovata' });

    if (req.session.user.id !== ownerId) {
      return res.status(403).json({ error: 'Non sei il proprietario dell’asta' });
    }

    const out = await closeAuctionAndNotify(auctionId, 'MANUAL');
    return res.status(200).json(out);
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});
/**
 * @swagger
 * /items/auction/:id:
 *   get:
 *     tags: ["item"]
 *     summary: Vedere un asta
 *     description: RIchiede le informazioni di un asta specifica
 *     responses:
 *       200:
 *         description: dati presi con successo
 *       500:
 *   
 * 
 */
router.get(`/items/auction/:auctionId`,async(req, res)=>{
  try {
    const auctionId = req.params.auctionId
    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.send(await infoAuction(auctionId))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /items/auction/createAuction:
 *   post:
 *     tags: ["item"]
 *     summary: Apre una nuova asta
 *     description: Crea una nuova asta se l'oggetto scelto appartiene all'utente loggato
 *     responses:
 *       200:
 *         description: Info Modificate
 *       500:
 *   
 * 
 */
/*router.post('/items/auction/newOffer', isAuthenticated, async(req, res) => {
  try {
    const userId = req.session.user.id
    const { auctionId, price } = req.body
    

    const auction = await infoAuction(auctionId)


    if (auction.length > 0 || auction.dataF) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Asta ineistente' }))
    }

    if(!auction.aperta){
      res.statusCode = 400
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Asta chiusa' }))      
    }

   

    const offer = (auction.fk_offerta === null)? null : await infoOffer(auction.fk_offerta)

    if(offer === null && auction.minPrezzo >= price ){
      const newOff = await newOffer(userId, auctionId, price)
    } else if (offer.valore < price){
      const newOff = await newOffer(userId, auctionId, price)
    }else{
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Valore dell\' offerta insufficente' }))
    }
    const winningOffer = await findOffer(userId, auctionId, price)
    const newWinner = await changeWinningOffer (winningOffer.id , auctionId)

    
    //data finale dell'asta
    const input = auction.dataF
    const [datePart, timePart] = input.split(" ")
    let [year, month, day] = datePart.split(".")
    let [hour, minute] = timePart.split(":")
    const inputDate = new Date(year, month - 1, day, hour-1, minute);
    
    //now date
    const now = new Date()

    if (inputDate <= now){
      inputDate.setHours(inputDate.getHours() + 1)
      const result = `${inputDate.getFullYear()}.${inputDate.getMonth() + 1}.${inputDate.getDay()} ${inputDate.getHours()}:${inputDate.getMinutes()}`
      const newTime = await setNewTime(auction.id, result)
    }



    res.statusCode = 200
    res.setHeader('Content-Type', 'application/json')
    res.end()
    
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})*/

router.post('/items/auction/newOffer', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id;
    const { auctionId, price } = req.body;

    const auction = await infoAuction(auctionId);

    if (!auction) {
      return res.status(404).json({ error: 'Asta inesistente' });
    }

    if (!auction.aperta) {
      return res.status(400).json({ error: 'Asta chiusa' });
    }

    // prezzo minimo: deve essere price >= minPrezzo (non il contrario)
    if (Number(price) < Number(auction.minPrezzo)+ 10.0) {
      return res.status(400).json({ error: 'Offerta sotto il prezzo minimo' });
    }

    // prendo l’offerta vincente attuale (se esiste)
    const currentWinning =
      auction.fk_offerta === null ? null : await infoOffer(auction.fk_offerta);

    if (currentWinning && Number(price) <= Number(currentWinning.valore)) {
      return res.status(400).json({ error: "Valore dell'offerta insufficiente" });
    }

    // inserisco nuova offerta
    const insert = await newOffer(userId, auctionId, price);
    await extendAuctionIfSniping(auctionId);

    // imposto subito come vincente (più affidabile di findOffer)
    await changeWinningOffer(insert.insertId, auctionId);

    // se vuoi estendere l'asta quando è scaduta, fallo correttamente
    // (altrimenti puoi rimuovere questo blocco)
    const end = (auction.dataF ? auction.dataF : null);

    // parsing semplice compatibile con "YYYY.MM.DD HH:MM" o "YYYY-MM-DD HH:MM"
    const parse = (str) => {
      if (!str) return null;
      const [dp, tp] = str.split(" ");
      if (!dp || !tp) return null;
      const sep = dp.includes(".") ? "." : "-";
      const [y, m, d] = dp.split(sep).map(Number);
      const [hh, mm] = tp.split(":").map(Number);
      if (![y, m, d, hh, mm].every(n => Number.isFinite(n))) return null;
      return new Date(y, m - 1, d, hh, mm, 0);
    };

    const endDate = parse(end);
    const now = new Date();

    // se scaduta, la sposto a now + 1h (coerente e senza getDay())
    if (endDate && endDate <= now) {
      const newEnd = new Date(now.getTime() + 60 * 60 * 1000);

      const yyyy = newEnd.getFullYear();
      const mm = String(newEnd.getMonth() + 1).padStart(2, "0");
      const dd = String(newEnd.getDate()).padStart(2, "0");
      const HH = String(newEnd.getHours()).padStart(2, "0");
      const MM = String(newEnd.getMinutes()).padStart(2, "0");

      const formatted = `${yyyy}.${mm}.${dd} ${HH}:${MM}`;
      await setNewTime(auction.id, formatted);
    }

    return res.status(200).end();
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
});

router.get('/notifications', isAuthenticated, async (req, res) => {
  try {
    const [rows] = await con.query(
      `SELECT id, titolo, testo, tipo, createdAt
       FROM notifica
       WHERE fk_utente=?
       ORDER BY id DESC
       LIMIT 200`,
      [req.session.user.id]
    );
    res.status(200).json(rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: String(err) });
  }
});

export { router }
