/**
 * @swagger
 * components:
 *   schemas:
 *     user:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description : Auto generated by the database
 *         username:
 *           type: string
 *         password:
 *           type: string
 *         nome:
 *           type: string
 *         cognome:
 *           type: string
 *     message:
 *       type: object
 *       properties:
 *         id:
 *           type: integer
 *           description : Auto generated by the database
 *         fk_utente:
 *           type: integer
 *         fk_chat:
 *           type: integer
 *         testo:
 *           type: string
 */

import express, { request } from 'express'
import {
  getItemsForSaleByUserId,
  getUserByUsername,
  getAuthUserByUsername,
  getMessagesByChatId,
  getChatsByUserId,
  createMessage,
  isAuthenticated,
  createUser,
  getChatByUserIdAndChatId,
  validateUserCredentials,
  updateUserById,
  createChat,
  checkChatExist,
  getUserById,
  getChatByUsers
} from '../utils/user_utils.js'
import bcrypt from 'bcryptjs';
import multer from 'multer'

const upload = multer({ dest: 'uploads/users' });
/*const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "uploads/users");
  },
  filename: (req, file, cb) => {
    const ext = path.extname(file.originalname); // keeps .jpg / .png
    const fileName = crypto.randomBytes(16).toString("hex") + ext;
    cb(null, fileName);
  }
});

const upload = multer({ storage });*/

const router = express.Router()

/**
 * @swagger
 * /signup:
 *   post:
 *     tags: ["user"]
 *     summary: Registra un nuovo utente
 *     description: Crea un nuovo utente con i dati che gli vengono passate
 *     responses:
 *       201:
 *         description: Utente creato con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 username:
 *                   type: string
 *       500:
 *         description: Errore interno del server
 *       415:
 *         description: Errore nei campi
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 errore:
 *                   type: string
 */
router.post('/signup', upload.single('prod_img'), async (req, res) => {
  try {
    const { username, password, firstName, lastName } = req.body

    const now = new Date()
    const formattedDate = now.getFullYear() +
      '-' +
      (now.getMonth() + 1) +
      '-' +
      now.getDate() +
      ' ' +
      now.getHours() +
      ':' +
      now.getMinutes()


    const credentials = await validateUserCredentials(username, password, firstName, lastName, res)
    if (credentials.error != undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: credentials.error }))
    }

    const createdUser = await createUser(
      //`http://127.0.0.1:${process.env.SERVER_PORT}/uploads/users/${req.file.filename}`,
      `http://127.0.0.1:${process.env.BACKEND_PORT}/uploads/users/${req.file.filename}`,
      firstName,
      lastName,
      username,
      formattedDate,
      credentials.hash,
      credentials.salt
    )

    res.statusCode = 201
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(createdUser.serverStatus))
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /modify:
 *   patch:
 *     tags: ["user"]
 *     summary: Modifica delle informazioni relative all'utente
 *     description: Modifica i campi nella tabella utente relativi a chi ha fatto il login
 *     responses:
 *       204:
 *         description: Utente modificato con successo
 *       500:
 *         description: Errore interno del server
 *       415:
 *         description: Errore nei campi
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 error:
 *                   type: string
 */
router.patch('/modify', isAuthenticated, async (req, res) => {
  try {
    const { username, password, firstName, lastName } = req.body
    console.log(username)

    const credentials = await validateUserCredentials(username, password, firstName, lastName, res)

    if (credentials.error != undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: credentials.error }))
    }

    const updatedUser = await updateUserById(
      req.session.user.id,
      firstName,
      lastName,
      credentials.username,
      credentials.hash,
      credentials.salt
    )

    req.session.user = getAuthUserByUsername(username)
    req.session.save(() => {
      res.statusCode = 200
      res.setHeader('Content-Type', 'application/json')
      res.end(
        JSON.stringify({
          sessionId: req.session.id,
          username: req.session.user.username,
          userId: req.session.user.id
        })
      )
    })
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: err }))
  }
})

/**
 * @swagger
 * /login:
 *   get:
 *     tags: ["user"]
 *     summary: Autentica l'utente
 *     description: Controlla se nel db c'è un utente che possiede le credenziali che sono state mandate
 *     responses:
 *       200:
 *         description: Utente loggato con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *       500:
 *         description: Errore interno del server
 */
router.get('/login/:username/:password', async (req, res) => {
  try {
    const username = req.params.username
    const password = req.params.password

    if (!username || !password) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Username o password non inserite' }))
    }

    const authUser = await getAuthUserByUsername(username)
    if (authUser === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Username non presente' }))
    }

    //non necessario metterlo o salvare l'hash con bycript ma con altri sì
    /* const salt = checkUsr.salt
        const hash_check = bcrypt.hashSync(password,salt)
        hash = hash_check */

    if (!bcrypt.compareSync(password, authUser.pswd)) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Credenziali inserite errate' }))
    }
    req.session.user = authUser
    req.session.save(() => {
      res.statusCode = 200
      res.setHeader('Content-Type', 'application/json')
      res.end(
        JSON.stringify({
          sessionId: req.session.id,
          username: req.session.user.username,
          userId: req.session.user.id,
          foto: req.session.user.foto

        })
      )
    })
  } catch (error) {
    console.error(error)
    res.statusCode = 500
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify({ error: error }))
  }
})

/**
 * @swagger
 * /logout:
 *   get:
 *     tags: ["user"]
 *     summary: Logout utente
 *     description: Disconnette l'utente dalla attuale sessione in funzione
 *     responses:
 *       200:
 *         description: Utente disconnesso con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *       500:
 *         description: Errore interno del server
 */
router.get('/logout', isAuthenticated, async (req, res) => {
  req.session.destroy(err => {
    if (err) {
      res.statusCode = 500
      res.setHeader('Content-Type', 'application/json')
      res.end(JSON.stringify({ error: err }))
    }
    res.clearCookie('connect.sid')
    res.statusCode = 300
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify('Logout eseguito correttamente'))
  })
})

/**
 * @swagger
 * /user:
 *   get:
 *     tags: ["user"]
 *     summary: Ritorna le informazioni di un'utente
 *     description: Ritorna username e id assieme alla lista di tutti gli articoli in vendita
 *     responses:
 *       200:
 *         description: informazioni recuperata
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 username:
 *                   type: string
 *                 aquistabili:
 *                   type: array
 *                   items:
 *                     type: object
 *                     properties:
 *                       id:
 *                         type: integer
 *                       fk_utente:
 *                         type: integer
 *                       prezzo:
 *                         type: float
 *                       immagine:
 *                         type: string
 *                       descrizione:
 *                         type: string
 *       500:
 *         description: Errore interno del server
 */
router.get('/user/:username', async (req, res) => {
  try {
    const username = req.params.username
    const user = await getUserByUsername(username)

    if (user === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Utente inesistente' }))
    }

    const userProfile = {
      id: user.id,
      name: user.nome,
      surname: user.cognome,
      username: user.username,
      foto: user.foto,
      itemsForSale: await getItemsForSaleByUserId(user.id)
    }

    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(userProfile))
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /chats:
 *   get:
 *     tags: ["message"]
 *     summary: Ritorna tutte le chat
 *     description: Select nel db che cerca tutte le chat con uno dei due utenti uguale all'id dell'utente
 *     responses:
 *       200:
 *         description: Messaggi recuperati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   fk_utente1:
 *                     type: integer
 *                   fk_utente2:
 *                     type: integer
 *       500:
 *         description: Errore interno del server
 */
router.get('/chats', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const chats = await getChatsByUserId(userId)

    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(chats))
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /messages/{chatId}:
 *   get:
 *     tags: ["message"]
 *     summary: Ritorna la chat dal suo id
 *     description: Ritorna tutti i messaggi di una chat fra due utenti
 *     responses:
 *       200:
 *         description: Messaggi recuperati con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   id:
 *                     type: integer
 *                   testo:
 *                     type: string
 *                   data:
 *                     type: string
 *                   fk_utente:
 *                     type: integer
 *                   fk_chat:
 *                     type: integer
 *       500:
 *         description: Errore interno del server
*/
router.get('/messages/:chatId', isAuthenticated, async (req, res) => {
  try {
    const chatId = req.params.chatId
    const userId = req.session.user.id

    const messages = await getMessagesByChatId(chatId)
    const chatAccess = await getChatByUserIdAndChatId(userId, chatId)

    if (messages === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Chat inesisistente' }))
    }

    if (chatAccess === undefined) {
      console.log(userId)
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: "Chat non appartenente all'utente loggato" }))
    }

    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(messages))
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /messages:
 *   post:
 *     tags: ["message"]
 *     summary: Invia un messaggio
 *     description: Aggiunge un messaggio alla chat
 *     responses:
 *       204:
 *         description: Messaggo inviato
 *       500:
 *         description: Errore interno del server
*/
router.post('/messages', isAuthenticated, async (req, res) => {
  try {
    const userId = req.session.user.id
    const { text, chatId } = req.body

    const messages = await getMessagesByChatId(chatId)
    const chatAccess = await getChatByUserIdAndChatId(userId, chatId)

    if (messages === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Chat inesisistente' }))
    }

    if (chatAccess === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: "Chat non appartenente all'utente loggato" }))
    }

    const now = new Date()
    const formattedDate =
      now.getFullYear() + +
      '-' +
      (now.getMonth() + 1) +
      '-' +
      now.getDate() +
      ' ' +
      now.getHours() +
      ':' +
      now.getMinutes()

    await createMessage(text, formattedDate, userId, chatId)
    res.end()
  } catch (error) {
    console.error(error)
  }
})

/**
 * @swagger
 * /chats:
 *   post:
 *     tags: ["message"]
 *     summary: Crea una nuova chat
 *     description: Crea una nuova chat fra due utenti nel db
 *     responses:
 *       201:
 *         description: Creazione eseguita con successo
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 id:
 *                   type: integer
 *                 fk_utente1:
 *                   type: integer
 *                 fk_utente2:
 *                   type: integer
 *       500:
 *         description: Errore interno del server
 */
router.post('/chats', isAuthenticated, async (req, res) => {
  try {
    const { userId2 } = req.body
    const userId1 = req.session.user.id
    const chatExist = await checkChatExist(userId2, userId1)

    if (chatExist.length > 0) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: "Chat già esistente" }))
    }
    const chat = await createChat(userId1, userId2)

    res.setHeader('Content-Type', 'application/json')
    res.status(201)
    res.end(JSON.stringify(chat))
  } catch (error) {
    console.error(error)
  }
})





router.get("/checkAuth", (req, res) => {
  if (req.session.user) {
    res.status(200).json({ loggedIn: true, username: req.session.user.username, foto: req.session.user.foto });
    console.log("SESSION USER:", req.session.user);
  } else {
    res.status(200).json({ loggedIn: false });
  }
});


router.get('/userId/:id', async (req, res) => {
  try {
    const id = req.params.id
    const user = await getUserById(id)

    if (user === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Utente inesistente' }))
    }

    const userProfile = {
      id: user.id,
      name: user.nome,
      surname: user.cognome,
      username: user.username,
      foto: user.foto,
      itemsForSale: await getItemsForSaleByUserId(user.id)
    }

    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(userProfile))
  } catch (error) {
    console.error(error)
  }
})

router.get('/chatMessages/:user1', isAuthenticated, async (req, res) => {
  try {
    const user1 = req.params.user1
    const user2 = req.session.user.id

    let chatId = await getChatByUsers(user1, user2)
    if(chatId.length == 0){
      const chat = await createChat(user1, user2)
      chatId = await getChatByUsers(user1, user2)
    }
    
    const messages = await getMessagesByChatId(chatId.id)

    if (messages === undefined) {
      res.statusCode = 401
      res.setHeader('Content-Type', 'application/json')
      return res.end(JSON.stringify({ error: 'Chat inesisistente e impossibile crearla' }))
    }

    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(messages))
  } catch (error) {
    console.error(error)
  }
})

export { router }
